apiVersion: v1
kind: Pod
metadata:
    name: flask-pod
    labels: 
      env: dev
      server: app
spec:
     containers:
     - name: flask 
       image: csporg/flask:master_1
       ports:
       - containerPort: 5001
