apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csp 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cloudstonesorg/csp-deployments.git       
    targetRevision: main    
    path: apps/csp
  destination:
    server: https://kubernetes.default.svc   
    namespace: csp   
  syncPolicy:
  syncOptions:
      - CreateNamespace=true
  automated:
    prune: true
    selfHeal: true
