apiVersion: v1
kind: ReplicationController
metadata:
 name: myrc
spec: 
    replicas: 2
    selector:
      server: web
    template:
      metadata:
        labels:
           env: Test
           server: web
      spec:    
         containers:
         - name: http
           image: http
           ports:
           - containerPort: 80
