apiVersion: v1
kind: Pod
metadata:
    name: mysql-pod
    labels: 
      env: dev
      server: db
spec:
     containers:
     - name: mysql 
       image: csporg/mysql:master_1
       env:
       - name: MYSQL_ROOT_PASSWORD
         value: Root_123
       ports:
       - containerPort: 3306
